development:
  adapter: postgresql
  encoding: utf8
  database: secretsanta_development
  pool: 5


test: &TEST
  adapter: postgresql
  encoding: utf8
  database: secretsanta_test
  pool: 5


production:
  adapter: postgresql
  encoding: utf8
  database: secretsanta_production
  pool: 5
